## Пример заполнения файла config.yml

source: # Описание Source PG/Feed, пакеты отсюда будут сравниваться с DEST PG/Feed (config.example.yml#6)
  url: "http://localhost" # URL адрес инстанса Source PG
  api_key: "30a4c00a5ce95d038577fea1d671a567" # API_KEY с правами на фид описанный ниже ( View/Download,Add/Repackage,Overwrite/Delete )
  feed: "first-feed" # Имя Source Feed

destination: # Описание DEST PG/Feed, пакеты отсюда будут сравниваться с Source PG/Feed (config.example.yml#1)
  url: "http://localhost:8080" # URL адрес инстанса Dest PG
  api_key: "51960d3631983c7f7bcf2e20ae1e60e" # API_KEY с правами на фид описанный ниже ( View/Download,Add/Repackage,Overwrite/Delete )
  feed: "second-feed" # Имя Dest Feed