## Пример заполнения файла config.yml

SyncChain:
  - source: # Описание Source PG/Feed, пакеты отсюда будут сравниваться с DEST PG/Feed (config.example.yml#6)
      url: "http://localhost" # URL адрес инстанса Source PG
      apiKey: "30a4c00a5ce95d038577fea1d671a567" # API_KEY с правами на фид описанный ниже ( View/Download,Add/Repackage,Overwrite/Delete )
      feed: "first-feed" # Имя Source Feed
    destination: # Описание DEST PG/Feed, пакеты отсюда будут сравниваться с Source PG/Feed (config.example.yml#1)
      url: "http://localhost:8080" # URL адрес инстанса Dest PG
      apiKey: "51960d3631983c7f7bcf2e20ae1e60e" # API_KEY с правами на фид описанный ниже ( View/Download,Add/Repackage,Overwrite/Delete )
      feed: "second-feed" # Имя Dest Feed

  - source: # Тоже что и выше.
      url: "http://localhost:8081"
      apiKey: "0dae18212a6f41ec8e2aaae8624614cf91d63205"
      feed: "first-sec-feed"
    destination:
      url: "http://localhost:8083"
      apiKey: "28e868cd710575c58881cf24ba358d9ecfb93af7"
      feed: "third-sec-feed"

# тут можно добавить ещё несколько цепочек синхронизации
#  - source:
#      url: ""
#      apiKey: ""
#      feed: ""
#    destination:
#      url: ""
#      apiKey: ""
#      feed: ""

# Ниже конфиг один на все цепочки
ProceedPackageLimit: 10 # Кол-во обрабатываемых параллельно пакетов

timeout: # Конфигурация таймаутов
  webRequestTimeout: 30 # Таймаут обращений к апи
  iterationTimeout: 120 # Пауза между синхронизациями \\ immutable!!! Изменение этого поля не попадает в цикл без перезагрузки

retention: # Конфигурация отчистки версий старше указанного лимита
  enabled: true # Включение
  dry-run: false # Отчистка без удаления пакетов, только логирование
  versionLimit: 2 # Кол-во версий, которые будут храниться, всё что старше будет удалено.