## Пример заполнения файла config.yml
## P.S - каждая строка начинается в lowerCase
syncChain:
  - source: # Описание Source PG/Feed, пакеты отсюда будут сравниваться с DEST PG/Feed
      url: "http://localhost" # URL адрес инстанса Source PG
      apiKey: "30a4c00a5ce95d038577" # API_KEY с правами на фид описанный ниже ( View/Download,Add/Repackage,Overwrite/Delete )
      feed: "first-feed" # Имя Source Feed
    destination: # Описание DEST PG/Feed, пакеты отсюда будут сравниваться с Source PG/Feed
      url: "http://localhost:8080" # URL адрес инстанса Dest PG
      apiKey: "51960d3631983c7f7bcf2" # API_KEY с правами на фид описанный ниже ( View/Download,Add/Repackage,Overwrite/Delete )
      feed: "second-feed" # Имя Dest Feed
    type: "upack" # тип синхронизируемого фида. Доступные "nuget", "upack", "assets".

  - source: # Тоже что и выше.
      url: "http://localhost:8081"
      apiKey: "0dae18212a6f41ec8e2aaae8624614cf91d63205"
      feed: "first-sec-feed"
    destination:
      url: "http://localhost:8083"
      apiKey: "28e868cd710575c58881cf24ba358d9ecfb93af7"
      feed: "third-sec-feed"
    type: "nuget"

# тут можно добавить ещё несколько цепочек синхронизации
#  - source:
#      url: ""
#      apiKey: ""
#      feed: ""
#    destination:
#      url: ""
#      apiKey: ""
#      feed: ""
#    type: "nuget"

# Ниже конфиг один на все цепочки
proceedPackageLimit: 10 # Кол-во обрабатываемых параллельно пакетов. Снижение этого параметра снижает общую нагрузку на ресурсы хоста
proceedPackageVersion: 1 # Кол-во версий пакета обрабатываемых параллельно. Снижение этого параметра снижает общую нагрузку на ресурсы хоста


timeout: # Конфигурация таймаутов
  webRequestTimeout: 15 # Таймаут обращений к апи
  iterationTimeout: 20 # Пауза между синхронизациями
  syncTimeout: 120 # Общий таймаут для операции синхронизации
  maxRetries: 5 # Кол-во повторов запросов вернувших не ожидаемый status-code

retention: # Конфигурация отчистки версий старше указанного лимита
  enabled: false # Включение
  dry-run: true # Отчистка без удаления пакетов, только логирование
  versionLimit: 2 # Кол-во версий, которые будут храниться, всё что старше будет удалено.

# P.S - лимит бесплатной версии ProGet - 10 запросов на удаление в час