name: release-please
on:
  push:
    branches:
      - main

concurrency:
  group: release-please-${{ github.ref_name }}

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          config-file: release-please-config.json
